[package]
name = "arthu-kovacs-rust-api"
version = "1.0.0"
authors = ["Your Name <your@site.com>"]
edition = "2018"

[dependencies]
http = "0.1"
vercel_lambda = "*"

[lib]
name = "user"
path = "user.rs"
