[package]
name = "arthur-kovacs-rust-api"
version = "1.0.0"
authors = ["Arthur Kovacs <hello@arthur.kovacs.is>"]
edition = "2021"

[dependencies]
http = "0.2.8"
vercel_lambda = {git = "https://github.com/ArthurianX/vercel-rust", branch = "main"}

[lib]
name = "user"
path = "user.rs"
