[package]
name = "arthur-kovacs-rust-api"
version = "1.0.0"
authors = ["Arthur Kovacs <hello@arthur.kovacs.is>"]
edition = "2018"

[dependencies]
http = "0.1"
vercel_lambda = "*"

[lib]
name = "user"
path = "user.rs"
